"""insert password hash

Revision ID: 35243757e9b1
Revises: 33be7cbbe04d
Create Date: 2026-05-29 16:03:32.622477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35243757e9b1'
down_revision: Union[str, Sequence[str], None] = '33be7cbbe04d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employees", sa.Column("password_hash", sa.String(255), nullable=True))
    op.execute("UPDATE employees SET password_hash = 'placeholder' where password_hash IS NULL")
    op.alter_column("employees", "password_hash", nullable=False)
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
