"""Role column addition

Revision ID: 713417714d6f
Revises: 1edaec03e890
Create Date: 2026-06-01 14:13:18.452887

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "713417714d6f"
down_revision: Union[str, Sequence[str], None] = "1edaec03e890"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_ROLE_ENUM = sa.Enum("UI", "UX", "DEVELOPER", "HR", name="employeerole")


def upgrade() -> None:
    """Upgrade schema."""
    _ROLE_ENUM.create(op.get_bind(), checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "employees",
        sa.Column("role", _ROLE_ENUM, server_default="DEVELOPER", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("employees", "role")
    # ### end Alembic commands ###
