"""init

Revision ID: 7615a07ad0d6
Revises: 6f976319614f
Create Date: 2026-05-28 17:28:44.508190

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7615a07ad0d6"
down_revision: Union[str, Sequence[str], None] = "6f976319614f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("address", sa.Column("employee_id", sa.Integer(), nullable=False))
    op.create_index(
        op.f("ix_address_employee_id"), "address", ["employee_id"], unique=False
    )
    op.create_foreign_key(
        None, "address", "employees", ["employee_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "address", type_="foreignkey")
    op.drop_index(op.f("ix_address_employee_id"), table_name="address")
    op.drop_column("address", "employee_id")
    # ### end Alembic commands ###
