"""init

Revision ID: 797fa2f2a61b
Revises:
Create Date: 2026-05-28 17:02:24.755902

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "797fa2f2a61b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("employees", sa.Column("age", sa.Integer(), nullable=True))
    op.alter_column(
        "employees", "email", existing_type=sa.VARCHAR(length=255), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "employees", "email", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    op.drop_column("employees", "age")
    # ### end Alembic commands ###
